name: flml_internet_checker
description: "Internet Connectivity Checking Package."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^2.3.8
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.0.0
  rounded_loading_button: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - packages/flml_internet_checker/assets/no_internet.json