name: flml_internet_checker
description: This package aims to check internet connection by just wrapping the widget with InternetChecker Widget without using any function calls inside your app"
version: 1.0.0
repository: https://github.com/FirstLogicMetaLabPvtLTD/flml_internet_checker

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # assets:
  #   - packages/flml_internet_checker/assets/